media:
  input: images
  output: /images

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: posts

    view:
      fields:
        - title
        - display_date
        - category

    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: subtitle
        label: Subtitle
        type: string
        required: true

      - name: excerpt
        label: Excerpt
        type: text
        required: true

      - name: category
        label: Category
        type: select
        required: true
        options:
          values:
            - value: DEVOPS & INFRASTRUCTURE
              label: DevOps & Infrastructure

            - value: CERTIFICATION & LAB LOG
              label: Certification & Lab Log

            - value: CLOUD & AWS
              label: Cloud & AWS

            - value: LINUX & SYSTEMS
              label: Linux & Systems

            - value: NETWORKING
              label: Networking

            - value: SOFTWARE ENGINEERING
              label: Software Engineering

      - name: display_date
        label: Display Date
        type: string
        required: true
        description: "Example: October 2026"

      - name: read_time
        label: Read Time
        type: string
        required: true
        description: "Example: 6 min read"

      - name: post_tags
        label: Tags
        type: string
        list: true
        description: "Example: #DevOps, #Docker, #Linux"

      - name: permalink
        label: Permalink
        type: string
        required: true
        description: "Example: /posts/my-new-post.html"

      - name: layout
        label: Layout
        type: string
        default: post.njk
        hidden: true

      - name: body
        label: Article
        type: rich-text
        required: true
